// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8_9OKDead0bVb_fO0lkMZWB1vcon0b6A',
    appId: '1:839481640912:android:f8c17aeeb09c7c605e9bd5',
    messagingSenderId: '839481640912',
    projectId: 'his-app-2549f',
    storageBucket: 'his-app-2549f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsr9BRcpD1mYdZNsAjfS9gYr-AyuSLmzw',
    appId: '1:839481640912:ios:e9844ef7d8b6146f5e9bd5',
    messagingSenderId: '839481640912',
    projectId: 'his-app-2549f',
    storageBucket: 'his-app-2549f.firebasestorage.app',
    androidClientId:
        '839481640912-bmaqee5184bsjaa5ptcfrcniftj4cqf4.apps.googleusercontent.com',
    iosClientId:
        '839481640912-hkvbk5jgqujuvss5adbrnt5ismaqqjmm.apps.googleusercontent.com',
    iosBundleId: 'com.mediacreation.his',
  );
}
